# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 16:03
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'get_latest_by': 'updated', 'ordering': ['-updated']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='comment',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.Topic', verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated'),
        ),
    ]
